import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wlBDHAHBJBhcDHATBhcBJAhyDHATBhcDHATBhcBiSAKBh9BheBcBhvAAAhgCh8Bi2ABBNAipBgmBwa4BdBdAeAhGCljAj0AhPBAAjKChpAiFA4Iv3AidAiBCADhoBhyADAiAAg2Aj6ADA14TBHAwYuFhwBDAhvBEBiCFhyAiyBEAnHFIAjuDIAhyFFAhvB');
