import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wkEQhKBPFMHBBBBhKBgiFDBBBhvIACABhKBgiHBBBBhKBgiFCCAChvHACAChKBgiHACAChKBgiHACAChKBgiRqJJgmDwapCcCcCcCg_QqYFixNhvGhZB4IwZBACh7PjxECChwFjZBjrBAA2QyNhvJh1Dh7NhuHinJhKHBBBBhKBkeNjwNhxNhxJ');
