import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('ghALAPAwVIAiUAizAgqCj1AlpBwbjBsVADBsEAjFBjLAEAk5BlhDitBBBjaBhABu7BICw3jAMAnEA3T7AkNBjiACAl9BhVBheAiXBiSCiPBj4A1JlACBioALAPAhAAwrzBwXuBh0Dh-CiABFAhpBABuEBEAh2B1QqBiEAhABKA1FZA');
